Vagrant.configure("2") do |config|

    config.vm.box = "bento/debian-12-arm64"

  # https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/01-prerequisites.md

    # jumpbox
    config.vm.define "jumpbox" do |jumpbox|
      jumpbox.vm.hostname = "jumpbox"
  
      jumpbox.vm.network "private_network", ip: "10.25.11.5", hostname: true

      jumpbox.vm.provider "parallels" do |prl|
        prl.name = "jumpbox"
        prl.memory = 512
        prl.cpus = 1
        prl.check_guest_tools = false
      end

      jumpbox.vm.provision "ansible" do |ansible|
        ansible.playbook = "provisioning/ansible/move_hosts_file.yaml"
        ansible.verbose = "v"
      end

      jumpbox.vm.provision "shell", inline: "echo hello from node *** JUMPBOX ***"
      jumpbox.vm.provision "shell", inline: "uname -mov"
      jumpbox.vm.provision "shell", inline: "ip a"
    end

    # server
    config.vm.define "server" do |server|
      server.vm.hostname = "server"
  
      server.vm.network "private_network", ip: "10.25.11.6", hostname: true

      server.vm.provider "parallels" do |prl|
        prl.name = "server"
        prl.memory = 2048
        prl.cpus = 1
        prl.check_guest_tools = false
      end

      server.vm.provision "ansible" do |ansible|
        ansible.playbook = "provisioning/ansible/move_hosts_file.yaml"
        ansible.verbose = "v"
      end

      server.vm.provision "shell", inline: "echo hello from node *** SERVER ***"
      server.vm.provision "shell", inline: "uname -mov"
      server.vm.provision "shell", inline: "ip a"
    end

  # 2 x Worker Nodes
  (0..1).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.hostname = "node-#{i}"

      node.vm.network "private_network", ip: "10.25.11.1#{i}", hostname: true

      node.vm.provider "parallels" do |prl|
        prl.name = "node-#{i}"
        prl.memory = 2048
        prl.cpus = 1
        prl.check_guest_tools = false
      end

      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "provisioning/ansible/move_hosts_file.yaml"
        ansible.verbose = "v"
      end

      node.vm.provision "shell", inline: "echo hello from node *** NODE-#{i} ***"
      node.vm.provision "shell", inline: "uname -mov"
      node.vm.provision "shell", inline: "ip a"
    end
  end

end